name:                sixty
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ollef/sixty#readme
license:             BSD3
author:              Olle Fredriksson
maintainer:          fredriksson.olle@gmail.com
copyright:           2019-2021 Olle Fredriksson
category:            Language, Compiler
extra-source-files:
- README.md
data-files:
- builtin/Builtin.vix
- rts/Sixten.Builtin.ll
- rts/main.ll
- rts/init.c

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -Wunused-packages
  - -funbox-strict-fields

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base >= 4.7 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - ansi-terminal
    - bytestring
    - constraints
    - constraints-extras
    - containers
    - data-default
    - dependent-hashmap
    - dependent-sum
    - dependent-sum-template
    - directory
    - filepath
    - fingertree
    - fsnotify
    - hashable
    - haskell-lsp
    - lens
    - lifted-async
    - lifted-base
    - llvm-hs-pretty
    - llvm-hs-pure
    - monad-control
    - mtl
    - parsers
    - persist
    - prettyprinter
    - process
    - random
    - rock
    - rope-utf16-splay
    - stm
    - template-haskell
    - temporary
    - text
    - time
    - transformers
    - transformers-base
    - unboxed-ref
    - unordered-containers

executables:
  sixty:
    source-dirs: app
    main: Main.hs
    dependencies:
      - optparse-applicative
      - sixty
      - text
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -H -A50m"

tests:
  test-sixty:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - directory
      - filepath
      - prettyprinter
      - rock
      - sixty
      - tasty
      - tasty-hunit
      - text
      - unordered-containers
