resolver: lts-17.5
packages:
- .
extra-deps:
- git: https://github.com/obsidiansystems/constraints-extras.git
  commit: 72d39c08f7b08a3a756f9019ad972d26a36fbbaa
- dependent-hashmap-0.1.0.1
- git: https://github.com/ollef/dependent-sum.git
  commit: b36c84a36ffdbb4de2bf7f7977bca7246b3b881a
  subdirs:
  - dependent-sum
  - dependent-sum-template
- llvm-hs-pretty-0.9.0.0
- rock-0.3.1.0
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
