resolver: lts-18.12
packages:
- .
extra-deps:
- dependent-hashmap-0.1.0.1
- llvm-hs-pretty-0.9.0.0
- rock-0.3.1.0
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
