name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache .stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.OS }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
          ${{ runner.OS }}-stack-

    - name: Add ~/.local/bin to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Setup Stack
      run: stack setup

    - name: Build dependencies
      run: stack test --dependencies-only --fast

    - name: Build
      run: stack test --no-run-tests --fast

    - name: Run tests
      run: stack test --fast
